# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

input_max_length: 8192,65536,8192,65536,131072,131072
datasets: alce_asqa_30,alce_asqa_345,alce_qampari_30,alce_qampari_345,alce_asqa_700,alce_qampari_700
generation_max_length: 300,300,300,300,300,300
test_files: data/alce/asqa_eval_gtr_top2000.json,data/alce/asqa_eval_gtr_top2000.json,data/alce/qampari_eval_gtr_top2000.json,data/alce/qampari_eval_gtr_top2000.json,data/alce/asqa_eval_gtr_top2000.json,data/alce/qampari_eval_gtr_top2000.json
demo_files: prompts/asqa_revised.json,prompts/asqa_revised.json,prompts/qampari_revised.json,prompts/qampari_revised.json,prompts/asqa_revised.json,prompts/qampari_revised.json
use_chat_template: true
max_test_samples: 100
shots: 2
stop_new_line: false
model_name_or_path: meta-llama/Llama-3.2-1B-Instruct
output_dir: output/Llama-3.2-1B-Instruct
use_tgi_or_vllm_serving: true
top_p: 0.95
temperature: 0
do_sample: false