# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

input_max_length: 8192,65536,131072
datasets: msmarco_rerank_psg,msmarco_rerank_psg,msmarco_rerank_psg
generation_max_length: 200,200,200
test_files: data/msmarco/test_reranking_data_k50_dep3.jsonl,data/msmarco/test_reranking_data_k600_dep3.jsonl,data/msmarco/test_reranking_data_k1000_dep3.jsonl
demo_files: data/msmarco/test_reranking_data_k10_dep3.jsonl,data/msmarco/test_reranking_data_k10_dep3.jsonl,data/msmarco/test_reranking_data_k10_dep3.jsonl
use_chat_template: true #false
max_test_samples: 100
shots: 2
stop_new_line: true
model_name_or_path: meta-llama/Llama-3.2-1B-Instruct
output_dir: output/Llama-3.2-1B-Instruct
use_tgi_or_vllm_serving: true
top_p: 0.95
temperature: 0
do_sample: false