# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

input_max_length: 8192,65536
datasets: kilt_nq,kilt_nq
generation_max_length: 20,20
test_files: data/kilt/nq-dev-multikilt_1000_k50_dep6.jsonl,data/kilt/nq-dev-multikilt_1000_k105_dep6.jsonl
demo_files: data/kilt/nq-train-multikilt_1000_k3_dep6.jsonl,data/kilt/nq-train-multikilt_1000_k3_dep6.jsonl
use_chat_template: false
max_test_samples: 100
shots: 2
stop_new_line: true
model_name_or_path: meta-llama/Llama-3.1-70B-Instruct
output_dir: output/test_tgi205_Llama-3.1-70B-Instruct
use_tgi_or_vllm_serving: true
top_p: 0.95 # got error with default 1.0
temperature: 0
do_sample: false
endpoint_host_ip: http://${host_ip}:${port}/v1/
